### ISSUE TITLE
calculate_padded_bounds results in Polygon with bounds empty 

### ISSUE THREAD

**Issue by ambientlight** [tilezen/tilequeue#194]
While playing around with tilequeue I want to perform a very simple pre-generation. 
The `tilequeue process`'s **DataFetcher worker** will fail with `IndexError: tuple index out of range`
The full stack trace:
```
process - ERROR - Error fetching: 1/1/1 - Traceback (most recent call last): |   
/tilezen/tilequeue/tilequeue/worker.py", line 195, in __call__    fetch_data = self.fetcher(nominal_zoom, unpadded_bounds) |   
/tilezen/tilequeue/tilequeue/query.py", line 173, in __call__    sql_conns, self.io_pool, layer_data, zoom, unpadded_bounds) |   
/tilezen/tilequeue/tilequeue/query.py", line 127, in enqueue_queries    unpadded_bounds, layer_data, zoom) 
/tilezen/tilequeue/tilequeue/query.py", line 93, in build_feature_queries    query = query_generator(padded_bounds, zoom) |   
/tilezen/tilequeue/tilequeue/query.py", line 22, in __call__    return generate_query(self.start_zoom, self.template, bounds, zoom) |   
/tilezen/tilequeue/tilequeue/query.py", line 11, in generate_query    query = template.render(bounds=bounds, zoom=zoom) |   
File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render    return self.environment.handle_exception(exc_info, True) |   
File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception    reraise(exc_type, exc_value, tb) |   
File "../vector-datasource/queries/water.jinja2", line 16, in top-level template code    {{ ne_water_cols() }} |   
File "/usr/local/lib/python2.7/site-packages/jinja2/runtime.py", line 553, in _invoke    rv = self._func(*arguments) |   
File "../vector-datasource/queries/water.jinja2", line 6, in template    {% filter geometry %}{{ bounds['polygon']|bbox_padded_intersection('the_geom') }}{% endfilter %} AS __geometry__, |   
/tilezen/tilequeue/tilequeue/query.py", line 63, in jinja_filter_bbox_padded_intersection    padded_bounds.bounds, geometry_col_name, srid) |   
/tilezen/tilequeue/tilequeue/query.py", line 51, in jinja_filter_bbox_intersection    min_point = 'ST_MakePoint(%.12f, %.12f)' % (bounds[0], bounds[1]) | 
IndexError: tuple index out of range
```

Debugging it I have found that `padded_bounds` from **jinja_filter_bbox_padded_intersection** in **tilequeue/query.py** contain bounds as empty tuple. 

Is it related to my environment? It seems to be something quite fundamental there with geometry which is quite weird to go wrong. The geos version is **3.6.1** and python is **2.7.12**

**More debugging info:**
<img width="1326" alt="screen shot 2017-04-30 at 7 24 38 pm" src="https://cloud.githubusercontent.com/assets/14032724/25563968/e84e6824-2dda-11e7-8b9d-155aac95b2ee.png">

<img width="1318" alt="screen shot 2017-04-30 at 7 23 44 pm" src="https://cloud.githubusercontent.com/assets/14032724/25563972/07cb1bd4-2ddb-11e7-9a53-615b2c1f2ccc.png">

**config.yaml**:

```yaml
queue:
  # type can be `sqs`, `multisqs`, `file`, `mem`, or `redis`
  type: file
  name: fqueue
store:
  type: directory # Can also be `directory`, which would dump the tiles to disk.
  name: tiles
  path: ./tiles
  reduced-redundancy: true
  date-prefix: 19851026
tiles:
  seed:
    # can use any combination of the following options for the
    # tilequeue seed command

    # all tiles in a particular zoom range
    all:
      zoom-start: 2
      zoom-until: 4

    # whether the tiles that are seeded should also be added to the
    # tiles of interest, or just enqueued
    should-add-to-tiles-of-interest: true

    # how many threads to use when enqueueing
    n-threads: 4

    # whether the tiles should be unique in memory
    # when seeding many tiles that are known to be unique, this should
    # be set to false to save memory
    unique: true

  intersect:
    # directory path to where expired tile files are generated
    expired-location: ./expired-tiles/
    # the lowest zoom level to consider when enqueueing tiles to
    # process on update
    parent-zoom-until: 11

process:
  # number of simultaneous "querysets" to issue to the database.  The
  # query for each layer will be issued in parallel to the same
  # database. This can be 0 or unspecified, in which case the number
  # will be inferred from the number of database names configured
  # below.
  n-simultaneous-query-sets: 1
  # whether to print out the internal python queue sizes
  log-queue-sizes: true
  # and at what interval
  log-queue-sizes-interval-seconds: 30
  query-config: ../vector-datasource/queries.yaml
  template-path: ../vector-datasource/queries
  # whether to reload jinja query templates on each request. This
  # should be off in production.
  reload-templates: false
  # extensions of formats to generate
  # buffered Mapbox Vector Tiles are also possible by specifying mvtb
  formats: [mvt]
  # additionally, the data included for some formats expects to be
  # buffered. This is where buffers per layer or per geometry type can
  # be specified, with layers trumping geometry types
  buffer:
    mvtb:
      layer:
        earth: {point: 256}
        water: {point: 256}
        places: {point: 128}
      geometry:
        point: 64
        line: 8
        polygon: 8
logging:
  # logging.conf on this page:
  # https://docs.python.org/2/howto/logging.html#logging-basic-tutorial
  config: logging.conf.sample
redis:
  # stub or redis_client. The stub type can be useful for mocking out
  # tiles of interest and in flight enqueueing operations.
  type: stub
  host: localhost
  port: 6379
  db: 0
  cache-set-key: tilequeue.tiles-of-interest
# expected data source is postgresql
postgresql:
  host: localhost
  port: 5432
  # multiple databases can be specified, and these are iterated
  # through to balance query loads. This is useful when connecting to
  # pgbouncer, which can dispatch to different back end databases
  # based on the name.
  dbnames: [osm]
  user: osm
  password:

# Set the metatile size to 1 to have tilequeue save metatiles to storage rather
# than individual tiles. This can have major benefits for reducing the number of
# writes to disk. Set the size to null, or omit the entry, to disable metatile
# writing and store individual tiles.
metatile:
  # Only metatiles of size 1 are currently supported, although other sizes may
  # be available in the future.
  size: null

  # if this is set to true, then tilequeue will write the individual formats in
  # addition to the metatile. this can be useful when gracefully "cutting over"
  # to a metatile-based system from an individual format based one.
  store_metatile_and_originals: false
```

I also had to modify the `default_buffer_size` at **command.py:568** since I disabled the metatile
```python
# default_queue_buffer_size = max(1, 128 >> (2 * cfg.metatile_size)) 
default_queue_buffer_size = 64
```

**Comment by ambientlight** [comment]
Ok ok, indeed it is environment issue. When executing `tilequeue process` under `env` inside `tileserver` the generation succeeded.

**Comment by rmarianski** [comment]
Glad you got it sorted out!
