### ISSUE TITLE
unpack error for empty bounds

### ISSUE THREAD

**Issue by rmarianski** [tilezen/tilequeue#286]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/worker.py", line 238, in __call__    for fetch, data in self.fetcher.fetch_tiles(all_data) :
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/query/rawr.py", line 638, in fetch_tiles    self.label_placement_layers)
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/query/rawr.py", line 491, in __init__    self.layers_index.index(self.osm, self.layers_index_source)
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/query/rawr.py", line 374, in index    self._index_feature(feature, osm, source)
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/query/rawr.py", line 422, in _index_feature    tiles = shape_tile_coverage(shape, zoom, self.tile_pyramid.tile())
  File "/usr/local/lib/python2.7/dist-packages/raw_tiles/tile.py", line 67, in shape_tile_coverage    minx, miny, maxx, maxy = shape.bounds
ValueError: need more than 0 values to unpack
```

Looks like bounds can be empty sometimes at this point in the code. Coords where this is happening:

* 10/512/512
* 10/512/511

**Comment by nvkelso** [comment]
Closed via #14.
