### ISSUE TITLE
Error determining geometry type for geometry collection

### ISSUE THREAD

**Issue by rmarianski** [tilezen/tilequeue#292]
Noticed the stack trace below in the logs.

```
Traceback (most recent call last): 
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/worker.py", line 370, in __call__    cut_coords, self.buffer_cfg, self.output_calc_mapping)
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/process.py", line 475, in process_coord    unpadded_bounds, cut_coords, buffer_cfg, extra_data, scale)
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/process.py", line 451, in format_coord    scale, buffer_cfg)
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/process.py", line 431, in _cut_child_tiles    feature_layers, unpadded_cut_bounds, meters_per_pixel_dim, buffer_cfg)
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/process.py", line 114, in _cut_coord    normalize_geometry_type(shape.type)]
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/tile.py", line 346, in normalize_geometry_type    'normalize_geometry_type: unknown geometry %s' % geom_type
AssertionError: normalize_geometry_type: unknown geometry GeometryCollection
```

**Comment by rmarianski** [comment]
I should have noted the coordinates that generated the error:

* 15/9446/12524
* 15/9447/12524
