### ISSUE TITLE
wkb shape type error

### ISSUE THREAD

**Issue by rmarianski** [tilezen/tilequeue#307]
```
Traceback (most recent call last): 
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/worker.py", line 315, in __call__    for fetch, data in self.fetcher.fetch_tiles(all_data):
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/query/rawr.py", line 763, in fetch_tiles    self.label_placement_layers, self.indexes_cfg)
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/query/rawr.py", line 607, in __init__    layers, tables, tile_pyramid, index_cfg))
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/query/rawr.py", line 574, in simple_index    index_table(table.rows, index)
  File "/usr/local/lib/python2.7/dist-packages/raw_tiles/index/index.py", line 33, in index_table    index.add_row(*obj)
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/query/rawr.py", line 441, in add_row    shape_type = wkb_shape_type(shape_wkb)
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/query/common.py", line 60, in wkb_shape_type    assert False, "WKB shape type %d not understood." % (typ,)
AssertionError: WKB shape type 7 not understood.
```

**Comment by zerebubuth** [comment]
The issue was that the [shape type detection code](https://github.com/tilezen/tilequeue/blob/00ac13223f9f2f0c4e64e77b8fa0381d39c8047e/tilequeue/query/common.py#L45-L60) wasn't written with `GeometryCollection`s (type 7) in mind. We probably don't want geometry collections in the RAWR tiles at all, so we might have to put some protection against them upstream in the RAWR tile generation code.
