### ISSUE TITLE
Requirements ImportError when collecting edtf

### ISSUE THREAD

**Issue by kurthalex** [tilezen/tilequeue#68]
(test_mapzen) @dskd ➜  tilequeue git:(master) pip install -e . 
Obtaining file:///home/akurth/tmp/tilequeue
Collecting boto (from tilequeue==0.7.1)
  Using cached boto-2.39.0-py2.py3-none-any.whl
Collecting edtf (from tilequeue==0.7.1)
  Using cached edtf-0.9.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-fCWrVm/edtf/setup.py", line 26, in <module>
        from edtf import **version**
      File "/tmp/pip-build-fCWrVm/edtf/edtf/**init**.py", line 3, in <module>
        from edtf_date import EDTFDate
      File "/tmp/pip-build-fCWrVm/edtf/edtf/edtf_date.py", line 2, in <module>
        from dateutil.relativedelta import relativedelta
    ImportError: No module named dateutil.relativedelta

**Comment by zerebubuth** [comment]
It seems to be a problem with the EDTF package [importing dateutil during setup](https://github.com/ixc/python-edtf/commit/fffa4d209899853217e38c341e02878bd512f0ce) - it's an issue which has been fixed on the Github master, but not released yet. We found the work-around was to manually install dateutil before trying to install tilequeue or edtf.

Hope that helps!

**Comment by nvkelso** [comment]
Closing for inactivity.
